### ISSUE TITLE
简单优化下写法

### ISSUE THREAD

**Issue by ryuushihou** [TECNB/Habeet#1]
这几个文件可以利用lombok来简化get set
可以给个pr权限吗

<img width="636" alt="image" src="https://github.com/TECNB/Habeet/assets/113272024/4402c891-daac-46a9-8071-de1d502a8f76">

**Comment by TECNB** [comment]
实体类里的get set方法我是用插件根据数据库直接生成的😂
RespDto类里我倒是直接用@Data简化了

**Comment by ryuushihou** [comment]
> 
啊 哈哈  其实都一样 只不过更统一一些。

**Comment by TECNB** [comment]
现在应该可以pr了🫡

**Comment by ryuushihou** [comment]
好的  你还木有写readme呐哈哈

**Comment by TECNB** [comment]
在赶了在赶了，本来以为没人看，我就懒得写了🙃

**Comment by ryuushihou** [comment]
哈哈 刚开始玩这个  挺有意思的每天看看别人的项目  共同学习！

**Comment by ryuushihou** [comment]
issue #1  的pr提了哈 你看没有问题的话 你就merge就可以了 就是去掉了自动生成的getset 改为了@Data

**Comment by ryuushihou** [comment]
merged
