### ISSUE TITLE
主类@MapperScan（XXX）的其他方案

### ISSUE THREAD

**Issue by ryuushihou** [TECNB/Habeet#2]
启动类里的扫描mapper可以 我觉得利用@mapper 写在mapper上面 这样以后万一如果mapper换地方的话 不需要再修改这里了
<img width="743" alt="image" src="https://github.com/TECNB/Habeet/assets/113272024/447bc50f-46cd-4d62-98f8-4f41a0ef2c4a">

**Comment by TECNB** [comment]
我记得一开始我是@Mapper来写的，后面在服务器上运行会出现问题，也不知道为什么，我就改写法了😔

**Comment by ryuushihou** [comment]
应该不会吧 我晚一点试试 顺便跑一下你这个

**Comment by ryuushihou** [comment]
不好意思 你现在@MapperScan是更好的选择  因为@mapper需要在每个mapper接口上添加 比较麻烦
