### ISSUE TITLE
请教下前端模块运行的问题

### ISSUE THREAD

**Issue by ryuushihou** [TECNB/Habeet#4]
兄弟 下面的除了vue以外的2个ui相关的环境配好之后npm run serve就可以运行了吗？ 后端的小弟对前端知识不太行哈哈

<img width="605" alt="截屏2023-08-07 14 05 48" src="https://github.com/TECNB/Habeet/assets/113272024/5525cd18-cdb2-44e8-95ad-96d5ab437d46">

**Comment by TECNB** [comment]
需要用hbuilder这个编译器打开的

**Comment by ryuushihou** [comment]
前端项目用hbuilder打开运行  就可以了？

**Comment by TECNB** [comment]
对的对的，但是我小程序密钥给不了你，你本地应该跑不了这个小程序，你可以直接微信小程序搜Habeet来试试前端（不过我线上的小程序不是最新版，github上的这个版本还在审核中）

**Comment by ryuushihou** [comment]
确实 我本地运行是个白色的。。 哈哈
<img width="2188" alt="image" src="https://github.com/TECNB/Habeet/assets/113272024/14ab8b02-152b-4d72-a90a-9a9e8c3ea188">

**Comment by ryuushihou** [comment]
ddl和dml  可以分享下吗 你的数据  我本地想试下我issue提的那个  @mapper的问题  我看看我本地调用api会不会出现问题

**Comment by TECNB** [comment]
那我等下拖个数据库文件上来

**Comment by ryuushihou** [comment]
看了一下 现在的@MapperScan是更好的选择  @mapper需要在每个mapper接口上添加 比较麻烦。
